resolver: lts-14.13
packages:
- .
extra-deps:
- github-0.23
- binary-instances-1
- dhall-1.27.0
# see https://gitlab.com/robstewart57/gitlab-haskell/-/merge_requests/2
- git: https://gitlab.com/k-bx/gitlab-haskell
  commit: 22e1a5aecc42ac3a14dc15c92f4b98632b60bdb9
