resolver: lts-16.10
packages:
- .
extra-deps:
- github-0.26
- binary-instances-1.0.0.1
# see https://gitlab.com/robstewart57/gitlab-haskell/-/merge_requests/3
- git: https://gitlab.com/k-bx/gitlab-haskell
  commit: 65fd47031a768b0d13023400fc6f87e1be11932a
# allow-newer: true
